# Production-specific Docker Compose overrides
version: '3.8'

services:
  shortwavereport:
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=warn
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    restart: always
    healthcheck:
      interval: 15s
      timeout: 5s
      retries: 5

  redis:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    restart: always
    command: redis-server --maxmemory 400mb --maxmemory-policy allkeys-lru

  prometheus:
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'

  grafana:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-shortwavereport123}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_ANALYTICS_REPORTING_ENABLED=false

  nginx:
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    restart: always